# Server
server:
  port: ${SERVER_PORT:8080}
  forward-headers-strategy: framework

app:
  cors:
    allowed-origins: "*"

# Spring
spring:
  application:
    name: ${APP_NAME:@project.artifactId@}
    version: ${APP_VERSION:@project.version@}

  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/${DB_NAME:prep}?currentSchema=prep_assessment}
    username: ${DB_USER:prep}
    password: ${DB_PASS:prep}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        generate_statistics: false
        show_sql: true
        format_sql: true
        check_nullability: true
        hbm2ddl:
          auto: validate

  # Liquibase
  liquibase:
    enabled: true
    liquibase-schema: public
    database-change-log-table: prep_some_log
    database-change-log-lock-table: prep_some_lock
    change-log: classpath:db/changelog.yaml

# Logging
logging:
  level:
    root: ${LOGGING_LEVEL_DEFAULT:INFO}
    org:
      springframework: INFO
      hibernate: INFO
      postgresql: WARN
      apache.tomcat.util: WARN
  pattern:
    console: "%d{ISO8601} %-5level [%t] %-30.30logger{29}: %msg%n%throwable"