insert into learning_tracks (code, title, description)
values
    ('BACKEND_JAVA', 'Backend-разработка на Java',
     'Подготовка к разработке серверных приложений на Java, Spring Boot, SQL и REST API.'),
    ('FRONTEND_REACT', 'Frontend-разработка на React',
     'Подготовка к созданию пользовательских интерфейсов на JavaScript, TypeScript и React.'),
    ('DATA_ANALYTICS', 'Аналитика данных',
     'Подготовка к работе с данными, SQL, статистикой и визуализацией.')
on conflict (code) do update
set title = excluded.title,
    description = excluded.description,
    updated_at = now();

insert into topics (title, description)
values
    ('Java Core', 'Синтаксис Java, ООП, коллекции, исключения и базовые механизмы платформы.'),
    ('Spring Boot', 'Создание REST API, dependency injection, работа со слоями приложения.'),
    ('SQL и базы данных', 'Реляционная модель, запросы, соединения таблиц, индексы и транзакции.'),
    ('HTTP и REST API', 'Клиент-серверное взаимодействие, методы HTTP, статусы ответов и проектирование API.'),
    ('JavaScript Core', 'Типы данных, функции, область видимости, промисы и работа с DOM.'),
    ('React', 'Компоненты, props, state, hooks и построение SPA.'),
    ('Статистика', 'Средние значения, дисперсия, вероятности, выборки и проверка гипотез.'),
    ('Визуализация данных', 'Графики, выбор визуальных форм и интерпретация аналитических дашбордов.')
on conflict (title) do update
set description = excluded.description,
    updated_at = now();

insert into learning_track_topics (learning_track_id, topic_id)
select lt.id, t.id
from (
    values
        ('BACKEND_JAVA', 'Java Core'),
        ('BACKEND_JAVA', 'Spring Boot'),
        ('BACKEND_JAVA', 'SQL и базы данных'),
        ('BACKEND_JAVA', 'HTTP и REST API'),
        ('FRONTEND_REACT', 'JavaScript Core'),
        ('FRONTEND_REACT', 'React'),
        ('FRONTEND_REACT', 'HTTP и REST API'),
        ('DATA_ANALYTICS', 'SQL и базы данных'),
        ('DATA_ANALYTICS', 'Статистика'),
        ('DATA_ANALYTICS', 'Визуализация данных')
) as relation_data(track_code, topic_title)
join learning_tracks lt on lt.code = relation_data.track_code
join topics t on t.title = relation_data.topic_title
where not exists (
    select 1
    from learning_track_topics ltt
    where ltt.learning_track_id = lt.id
      and ltt.topic_id = t.id
);

insert into tests (title, description, type, grade, topic_id, learning_track_id)
select test_data.title,
       test_data.description,
       test_data.type,
       test_data.grade,
       t.id,
       lt.id
from (
    values
        ('Диагностика Backend Java',
         'Стартовый тест по Java, Spring Boot, SQL и REST API для выбора индивидуального маршрута.',
         'DIAGNOSTIC', null, null, 'BACKEND_JAVA'),
        ('Java Core: базовый уровень',
         'Проверка знания ООП, коллекций, исключений и базового синтаксиса Java.',
         'REGULAR', 'JUNIOR', 'Java Core', null),
        ('Spring Boot: REST API',
         'Проверка понимания контроллеров, сервисов, DI и обработки HTTP-запросов.',
         'REGULAR', 'MIDDLE', 'Spring Boot', null),
        ('SQL: запросы и связи',
         'Проверка навыков выборки, фильтрации и соединения данных в реляционной базе.',
         'REGULAR', 'JUNIOR', 'SQL и базы данных', null),
        ('Диагностика Frontend React',
         'Стартовый тест по JavaScript, React и HTTP для оценки готовности к frontend-треку.',
         'DIAGNOSTIC', null, null, 'FRONTEND_REACT'),
        ('React: компоненты и hooks',
         'Проверка знания компонентов, props, state и базовых hooks.',
         'REGULAR', 'JUNIOR', 'React', null),
        ('Диагностика аналитика данных',
         'Стартовый тест по SQL, статистике и визуализации данных.',
         'DIAGNOSTIC', null, null, 'DATA_ANALYTICS'),
        ('Статистика: базовые понятия',
         'Проверка знания средних величин, дисперсии, вероятности и выборок.',
         'REGULAR', 'JUNIOR', 'Статистика', null)
) as test_data(title, description, type, grade, topic_title, track_code)
left join topics t on t.title = test_data.topic_title
left join learning_tracks lt on lt.code = test_data.track_code
where true
on conflict (title) do update
set description = excluded.description,
    type = excluded.type,
    grade = excluded.grade,
    topic_id = excluded.topic_id,
    learning_track_id = excluded.learning_track_id,
    updated_at = now();

insert into questions (test_id, topic_id, subtopic, grade, wording_question, serial_number)
select tests.id,
       topics.id,
       question_data.subtopic,
       question_data.grade,
       question_data.wording_question,
       question_data.serial_number
from (
    values
        ('Диагностика Backend Java', 'Java Core', 'ООП', 'JUNIOR',
         'Какой принцип ООП позволяет объекту скрывать внутреннее состояние и открывать доступ через методы?',
         1),
        ('Диагностика Backend Java', 'Spring Boot', 'Dependency Injection', 'MIDDLE',
         'Для чего в Spring чаще всего используется аннотация @Service?',
         2),
        ('Диагностика Backend Java', 'SQL и базы данных', 'JOIN', 'JUNIOR',
         'Какой тип JOIN вернет все строки из левой таблицы и совпадающие строки из правой?',
         3),
        ('Диагностика Backend Java', 'HTTP и REST API', 'HTTP methods', 'JUNIOR',
         'Какой HTTP-метод обычно используют для полного обновления существующего ресурса?',
         4),
        ('Java Core: базовый уровень', 'Java Core', 'Коллекции', 'JUNIOR',
         'Какая коллекция в Java хранит уникальные элементы без гарантии порядка?',
         1),
        ('Java Core: базовый уровень', 'Java Core', 'Исключения', 'JUNIOR',
         'Какой блок выполнится независимо от того, было выброшено исключение или нет?',
         2),
        ('Java Core: базовый уровень', 'Java Core', 'ООП', 'JUNIOR',
         'Что означает наследование в объектно-ориентированном программировании?',
         3),
        ('Spring Boot: REST API', 'Spring Boot', 'Controller layer', 'MIDDLE',
         'Какая аннотация Spring объединяет @Controller и @ResponseBody?',
         1),
        ('Spring Boot: REST API', 'Spring Boot', 'Bean lifecycle', 'MIDDLE',
         'Что делает контейнер Spring с классом, помеченным @Component?',
         2),
        ('Spring Boot: REST API', 'HTTP и REST API', 'Status codes', 'MIDDLE',
         'Какой HTTP-статус лучше всего подходит для успешного создания ресурса?',
         3),
        ('SQL: запросы и связи', 'SQL и базы данных', 'Filtering', 'JUNIOR',
         'Какое ключевое слово SQL используется для фильтрации строк до группировки?',
         1),
        ('SQL: запросы и связи', 'SQL и базы данных', 'Aggregation', 'JUNIOR',
         'Какую функцию используют для подсчета количества строк?',
         2),
        ('SQL: запросы и связи', 'SQL и базы данных', 'Transactions', 'MIDDLE',
         'Что делает команда COMMIT в транзакции?',
         3),
        ('Диагностика Frontend React', 'JavaScript Core', 'Promises', 'JUNIOR',
         'Что возвращает метод then у Promise?',
         1),
        ('Диагностика Frontend React', 'React', 'State', 'JUNIOR',
         'Какой hook в React чаще всего используют для хранения локального состояния компонента?',
         2),
        ('Диагностика Frontend React', 'HTTP и REST API', 'Status codes', 'JUNIOR',
         'Какой HTTP-статус означает, что запрошенный ресурс не найден?',
         3),
        ('React: компоненты и hooks', 'React', 'Props', 'JUNIOR',
         'Для чего props передаются в React-компонент?',
         1),
        ('React: компоненты и hooks', 'React', 'Hooks', 'JUNIOR',
         'Для чего используется useEffect?',
         2),
        ('React: компоненты и hooks', 'JavaScript Core', 'Immutability', 'JUNIOR',
         'Почему при обновлении массива в state обычно создают новый массив?',
         3),
        ('Диагностика аналитика данных', 'SQL и базы данных', 'SELECT', 'JUNIOR',
         'Какая команда SQL используется для выборки данных из таблицы?',
         1),
        ('Диагностика аналитика данных', 'Статистика', 'Mean', 'JUNIOR',
         'Что показывает среднее арифметическое числового набора?',
         2),
        ('Диагностика аналитика данных', 'Визуализация данных', 'Chart choice', 'JUNIOR',
         'Какой график обычно удобен для сравнения категорий между собой?',
         3),
        ('Статистика: базовые понятия', 'Статистика', 'Median', 'JUNIOR',
         'Что такое медиана набора чисел?',
         1),
        ('Статистика: базовые понятия', 'Статистика', 'Variance', 'JUNIOR',
         'Что описывает дисперсия?',
         2),
        ('Статистика: базовые понятия', 'Статистика', 'Sample', 'JUNIOR',
         'Что такое выборка в статистике?',
         3)
) as question_data(test_title, topic_title, subtopic, grade, wording_question, serial_number)
join tests on tests.title = question_data.test_title
join topics on topics.title = question_data.topic_title
where not exists (
    select 1
    from questions existing_question
    where existing_question.test_id = tests.id
      and existing_question.serial_number = question_data.serial_number
);

insert into answers (question_id, text, is_correct, explanation)
select questions.id,
       answer_data.text,
       answer_data.is_correct,
       answer_data.explanation
from (
    values
        ('Диагностика Backend Java', 1, 'Инкапсуляция', true,
         'Инкапсуляция скрывает детали реализации и предоставляет контролируемый доступ к данным.'),
        ('Диагностика Backend Java', 1, 'Наследование', false,
         'Наследование описывает переиспользование поведения родительского класса.'),
        ('Диагностика Backend Java', 1, 'Полиморфизм', false,
         'Полиморфизм позволяет работать с объектами разных типов через общий интерфейс.'),
        ('Диагностика Backend Java', 1, 'Композиция', false,
         'Композиция строит объект из других объектов, но не отвечает за скрытие состояния.'),
        ('Диагностика Backend Java', 2, 'Для пометки класса бизнес-логики как Spring bean', true,
         '@Service указывает, что класс относится к сервисному слою и должен управляться Spring-контейнером.'),
        ('Диагностика Backend Java', 2, 'Для описания таблицы базы данных', false,
         'Таблицы обычно описывают через @Entity.'),
        ('Диагностика Backend Java', 2, 'Для настройки HTTP-маршрута', false,
         'HTTP-маршруты чаще задают в контроллерах через @RequestMapping и похожие аннотации.'),
        ('Диагностика Backend Java', 2, 'Для запуска приложения', false,
         'Точку входа Spring Boot обычно помечают @SpringBootApplication.'),
        ('Диагностика Backend Java', 3, 'LEFT JOIN', true,
         'LEFT JOIN сохраняет все строки левой таблицы и добавляет совпадения из правой.'),
        ('Диагностика Backend Java', 3, 'INNER JOIN', false,
         'INNER JOIN возвращает только строки с совпадениями в обеих таблицах.'),
        ('Диагностика Backend Java', 3, 'RIGHT JOIN', false,
         'RIGHT JOIN сохраняет все строки правой таблицы.'),
        ('Диагностика Backend Java', 3, 'CROSS JOIN', false,
         'CROSS JOIN строит декартово произведение строк.'),
        ('Диагностика Backend Java', 4, 'PUT', true,
         'PUT обычно используют для полной замены или обновления ресурса по известному адресу.'),
        ('Диагностика Backend Java', 4, 'GET', false,
         'GET предназначен для получения ресурса.'),
        ('Диагностика Backend Java', 4, 'DELETE', false,
         'DELETE используют для удаления ресурса.'),
        ('Диагностика Backend Java', 4, 'OPTIONS', false,
         'OPTIONS описывает доступные параметры взаимодействия с ресурсом.'),
        ('Java Core: базовый уровень', 1, 'HashSet', true,
         'HashSet хранит уникальные элементы и не гарантирует порядок обхода.'),
        ('Java Core: базовый уровень', 1, 'ArrayList', false,
         'ArrayList допускает дубликаты и сохраняет порядок добавления.'),
        ('Java Core: базовый уровень', 1, 'LinkedList', false,
         'LinkedList также допускает дубликаты.'),
        ('Java Core: базовый уровень', 1, 'TreeMap', false,
         'TreeMap хранит пары ключ-значение, а не просто элементы множества.'),
        ('Java Core: базовый уровень', 2, 'finally', true,
         'Блок finally выполняется после try/catch почти всегда, даже если исключение было обработано.'),
        ('Java Core: базовый уровень', 2, 'catch', false,
         'catch выполняется только при перехвате подходящего исключения.'),
        ('Java Core: базовый уровень', 2, 'throw', false,
         'throw используется для явного выброса исключения.'),
        ('Java Core: базовый уровень', 2, 'throws', false,
         'throws объявляет возможные исключения в сигнатуре метода.'),
        ('Java Core: базовый уровень', 3, 'Возможность классу получать поля и методы родительского класса', true,
         'Наследование позволяет создавать новый класс на основе существующего.'),
        ('Java Core: базовый уровень', 3, 'Скрытие внутреннего состояния объекта', false,
         'Это описание инкапсуляции.'),
        ('Java Core: базовый уровень', 3, 'Создание объекта из нескольких независимых объектов', false,
         'Это ближе к композиции.'),
        ('Java Core: базовый уровень', 3, 'Преобразование примитивов в объекты', false,
         'Это boxing, а не наследование.'),
        ('Spring Boot: REST API', 1, '@RestController', true,
         '@RestController возвращает данные напрямую в тело HTTP-ответа.'),
        ('Spring Boot: REST API', 1, '@Service', false,
         '@Service применяют для сервисного слоя.'),
        ('Spring Boot: REST API', 1, '@Repository', false,
         '@Repository применяют для слоя доступа к данным.'),
        ('Spring Boot: REST API', 1, '@Entity', false,
         '@Entity описывает JPA-сущность.'),
        ('Spring Boot: REST API', 2, 'Создает bean и управляет его жизненным циклом', true,
         '@Component делает класс кандидатом на автоматическое обнаружение и регистрацию в контексте.'),
        ('Spring Boot: REST API', 2, 'Создает новую таблицу в базе данных', false,
         'Создание таблиц не является задачей @Component.'),
        ('Spring Boot: REST API', 2, 'Отключает dependency injection', false,
         '@Component как раз используется вместе с DI.'),
        ('Spring Boot: REST API', 2, 'Публикует endpoint без контроллера', false,
         'Endpoint обычно объявляют в контроллере.'),
        ('Spring Boot: REST API', 3, '201 Created', true,
         '201 Created означает, что ресурс успешно создан.'),
        ('Spring Boot: REST API', 3, '200 OK', false,
         '200 OK означает общий успешный ответ, но для создания точнее 201.'),
        ('Spring Boot: REST API', 3, '204 No Content', false,
         '204 означает успех без тела ответа.'),
        ('Spring Boot: REST API', 3, '404 Not Found', false,
         '404 означает, что ресурс не найден.'),
        ('SQL: запросы и связи', 1, 'WHERE', true,
         'WHERE фильтрует строки до группировки и агрегации.'),
        ('SQL: запросы и связи', 1, 'HAVING', false,
         'HAVING фильтрует группы после GROUP BY.'),
        ('SQL: запросы и связи', 1, 'ORDER BY', false,
         'ORDER BY сортирует результат.'),
        ('SQL: запросы и связи', 1, 'LIMIT', false,
         'LIMIT ограничивает количество строк в результате.'),
        ('SQL: запросы и связи', 2, 'COUNT', true,
         'COUNT считает количество строк или непустых значений.'),
        ('SQL: запросы и связи', 2, 'SUM', false,
         'SUM складывает числовые значения.'),
        ('SQL: запросы и связи', 2, 'AVG', false,
         'AVG вычисляет среднее значение.'),
        ('SQL: запросы и связи', 2, 'MAX', false,
         'MAX возвращает максимальное значение.'),
        ('SQL: запросы и связи', 3, 'Фиксирует изменения транзакции', true,
         'COMMIT делает изменения транзакции постоянными.'),
        ('SQL: запросы и связи', 3, 'Отменяет изменения транзакции', false,
         'Отмена изменений выполняется командой ROLLBACK.'),
        ('SQL: запросы и связи', 3, 'Создает индекс', false,
         'Индексы создают отдельной DDL-командой.'),
        ('SQL: запросы и связи', 3, 'Открывает новое соединение', false,
         'COMMIT не управляет соединением с базой.'),
        ('Диагностика Frontend React', 1, 'Новый Promise', true,
         'then возвращает Promise, что позволяет строить цепочки асинхронных операций.'),
        ('Диагностика Frontend React', 1, 'Всегда строку', false,
         'Тип результата зависит от обработчика, а then все равно возвращает Promise.'),
        ('Диагностика Frontend React', 1, 'DOM-элемент', false,
         'then не связан напрямую с DOM.'),
        ('Диагностика Frontend React', 1, 'HTTP-запрос', false,
         'HTTP-запрос может вернуть Promise, но then его не создает как запрос.'),
        ('Диагностика Frontend React', 2, 'useState', true,
         'useState хранит локальное состояние функционального компонента.'),
        ('Диагностика Frontend React', 2, 'useMemo', false,
         'useMemo мемоизирует вычисленное значение.'),
        ('Диагностика Frontend React', 2, 'useRef', false,
         'useRef хранит изменяемую ссылку, но не является основным hook для state.'),
        ('Диагностика Frontend React', 2, 'useCallback', false,
         'useCallback мемоизирует функцию.'),
        ('Диагностика Frontend React', 3, '404 Not Found', true,
         '404 означает, что сервер не нашел запрошенный ресурс.'),
        ('Диагностика Frontend React', 3, '201 Created', false,
         '201 означает успешное создание ресурса.'),
        ('Диагностика Frontend React', 3, '301 Moved Permanently', false,
         '301 означает постоянное перенаправление.'),
        ('Диагностика Frontend React', 3, '500 Internal Server Error', false,
         '500 означает ошибку на стороне сервера.'),
        ('React: компоненты и hooks', 1, 'Для передачи данных от родителя к дочернему компоненту', true,
         'Props позволяют параметризовать компонент данными извне.'),
        ('React: компоненты и hooks', 1, 'Для хранения глобальной базы данных', false,
         'Props не являются базой данных.'),
        ('React: компоненты и hooks', 1, 'Для прямого изменения DOM', false,
         'React обычно управляет DOM декларативно.'),
        ('React: компоненты и hooks', 1, 'Для подключения CSS-файлов', false,
         'Props не отвечают за подключение CSS.'),
        ('React: компоненты и hooks', 2, 'Для выполнения побочных эффектов после рендера', true,
         'useEffect подходит для запросов, подписок и синхронизации с внешними системами.'),
        ('React: компоненты и hooks', 2, 'Для объявления маршрутов Spring Boot', false,
         'Это относится к backend-разработке, а не к React hook.'),
        ('React: компоненты и hooks', 2, 'Для создания SQL-запросов', false,
         'useEffect не предназначен для генерации SQL.'),
        ('React: компоненты и hooks', 2, 'Для типизации props', false,
         'Типизация props обычно делается TypeScript или PropTypes.'),
        ('React: компоненты и hooks', 3, 'Чтобы React корректно увидел изменение ссылки и обновил UI', true,
         'Иммутабельное обновление помогает React сравнивать значения и запускать перерендер.'),
        ('React: компоненты и hooks', 3, 'Чтобы массив стал отсортированным автоматически', false,
         'Создание нового массива само по себе не сортирует данные.'),
        ('React: компоненты и hooks', 3, 'Чтобы отключить рендер компонента', false,
         'Обновление state обычно наоборот приводит к рендеру.'),
        ('React: компоненты и hooks', 3, 'Чтобы удалить все элементы массива', false,
         'Новый массив может содержать любые нужные элементы, не обязательно быть пустым.'),
        ('Диагностика аналитика данных', 1, 'SELECT', true,
         'SELECT выбирает данные из таблиц и выражений.'),
        ('Диагностика аналитика данных', 1, 'INSERT', false,
         'INSERT добавляет новые строки.'),
        ('Диагностика аналитика данных', 1, 'UPDATE', false,
         'UPDATE изменяет существующие строки.'),
        ('Диагностика аналитика данных', 1, 'DELETE', false,
         'DELETE удаляет строки.'),
        ('Диагностика аналитика данных', 2, 'Центр набора значений через сумму, деленную на количество', true,
         'Среднее арифметическое показывает типичный уровень значений, если выбросы не искажают картину.'),
        ('Диагностика аналитика данных', 2, 'Самое частое значение', false,
         'Самое частое значение называется модой.'),
        ('Диагностика аналитика данных', 2, 'Разницу между максимумом и минимумом', false,
         'Это размах.'),
        ('Диагностика аналитика данных', 2, 'Количество строк в таблице', false,
         'Количество наблюдений не является средним арифметическим.'),
        ('Диагностика аналитика данных', 3, 'Столбчатая диаграмма', true,
         'Столбчатая диаграмма хорошо подходит для сравнения значений по категориям.'),
        ('Диагностика аналитика данных', 3, 'Точечная диаграмма', false,
         'Точечная диаграмма чаще показывает связь двух числовых признаков.'),
        ('Диагностика аналитика данных', 3, 'Линейный график', false,
         'Линейный график чаще показывает динамику во времени.'),
        ('Диагностика аналитика данных', 3, 'Box plot', false,
         'Box plot полезен для распределений, но не самый простой выбор для сравнения категорий.'),
        ('Статистика: базовые понятия', 1, 'Значение, которое делит упорядоченный набор пополам', true,
         'Медиана находится в середине отсортированного набора или считается как среднее двух центральных значений.'),
        ('Статистика: базовые понятия', 1, 'Сумма всех значений', false,
         'Сумма не делит набор пополам.'),
        ('Статистика: базовые понятия', 1, 'Самое большое значение', false,
         'Самое большое значение называется максимумом.'),
        ('Статистика: базовые понятия', 1, 'Самое частое значение', false,
         'Самое частое значение называется модой.'),
        ('Статистика: базовые понятия', 2, 'Разброс значений относительно среднего', true,
         'Дисперсия показывает, насколько значения отклоняются от среднего.'),
        ('Статистика: базовые понятия', 2, 'Порядковый номер строки', false,
         'Порядковый номер не описывает разброс данных.'),
        ('Статистика: базовые понятия', 2, 'Название категории', false,
         'Категория не является числовой мерой вариативности.'),
        ('Статистика: базовые понятия', 2, 'Количество столбцов в таблице', false,
         'Количество столбцов не связано с дисперсией.'),
        ('Статистика: базовые понятия', 3, 'Часть генеральной совокупности, выбранная для анализа', true,
         'Выборка используется, когда исследовать всю совокупность дорого или невозможно.'),
        ('Статистика: базовые понятия', 3, 'Любая SQL-таблица', false,
         'SQL-таблица может хранить выборку, но сама по себе не определяет статистический термин.'),
        ('Статистика: базовые понятия', 3, 'Один график на дашборде', false,
         'График визуализирует данные, но не является выборкой.'),
        ('Статистика: базовые понятия', 3, 'Ошибка измерения', false,
         'Ошибка измерения не равна выборке.')
) as answer_data(test_title, serial_number, text, is_correct, explanation)
join tests on tests.title = answer_data.test_title
join questions on questions.test_id = tests.id
              and questions.serial_number = answer_data.serial_number
where not exists (
    select 1
    from answers existing_answer
    where existing_answer.question_id = questions.id
      and existing_answer.text = answer_data.text
);
